export const Mysimulations = [
  {
    id: "1",
    title: "Marketing Strategy Simulation",
    logo: "https://i.pinimg.com/1200x/c9/ab/30/c9ab30e7150b6810b3e871ffc91e7d29.jpg",
    role: "Marketing Intern",
    difficulty: "Beginner",
    lastActivity: 1764747603,
    progress: 48,
    status: "In Progress",
    companyName: "Company A",
    skills: ["SEO", "Content"],
    score: 85,
    lesson: ["Intro", "Campaign Basics"],
  },
  {
    id: "2",
    title: "AI Product Management Simulation",
    logo: "https://i.pinimg.com/736x/f7/ef/c8/f7efc85c852b7c5f1d0db8f5903a7a92.jpg",
    role: "AI Product Manager",
    difficulty: "Intermediate",
    lastActivity: 1764747543,
    progress: 100,
    status: "Completed",
    companyName: "Company B",
    skills: ["Roadmapping"],
    score: 92,
    lesson: ["Foundations"],
  },
  {
    id: "3",
    title: "Finance Analysis Simulation",
    logo: "https://i.pinimg.com/736x/c4/fd/d7/c4fdd774f3d194d5c80a9bc2d04f077e.jpg",
    role: "Financial Analyst",
    difficulty: "Advanced",
    lastActivity: 1764747483,
    progress: 100,
    status: "Completed",
    companyName: "Company C",
    skills: ["DCF", "Reporting"],
    score: 82,
    lesson: ["Valuation", "Statements"],
  },
  {
    id: "4",
    title: "Marketing Campaign Simulation",
    logo: "https://i.pinimg.com/1200x/00/d6/f1/00d6f13382a283b8d627b706e3076516.jpg",
    role: "Marketing Specialist",
    difficulty: "Intermediate",
    lastActivity: 1764747423,
    progress: 76,
    status: "In Progress",
    companyName: "Company D",
    skills: ["Ads", "Analytics"],
    score: 90,
    lesson: ["Channels", "Optimization"],
  },
];

export const simulationsRecomment = [
  {
    id: "1",
    title: "Marketing Strategy Simulation",
    logo: "https://i.pinimg.com/1200x/c9/ab/30/c9ab30e7150b6810b3e871ffc91e7d29.jpg",
    role: "Marketing Intern",
    difficulty: "Beginner",
    lastActivity: 1764747603,
    progress: 0,
    status: "not_registed",
    companyName: "Company A",
    skills: ["SEO", "Content", "DCF"],
    score: 0,
    lesson: ["Intro", "Campaign Basics"],
  },
  {
    id: "2",
    title: "AI Product Management Simulation",
    logo: "https://i.pinimg.com/736x/f7/ef/c8/f7efc85c852b7c5f1d0db8f5903a7a92.jpg",
    role: "AI Product Manager",
    difficulty: "Intermediate",
    lastActivity: 1764747543,
    progress: 0,
    status: "not_registed",
    companyName: "Company B",
    skills: ["Roadmapping", "Strategy"],
    score: 0,
    lesson: ["Foundations"],
  },
  {
    id: "3",
    title: "Finance Analysis Simulation",
    logo: "https://i.pinimg.com/736x/c4/fd/d7/c4fdd774f3d194d5c80a9bc2d04f077e.jpg",
    role: "Financial Analyst",
    difficulty: "Advanced",
    lastActivity: 1764747483,
    progress: 0,
    status: "not_registed",
    companyName: "Company C",
    skills: ["DCF", "Reporting"],
    score: 0,
    lesson: ["Valuation", "Statements"],
  },
  {
    id: "4",
    title: "Marketing Campaign Simulation",
    logo: "https://i.pinimg.com/1200x/00/d6/f1/00d6f13382a283b8d627b706e3076516.jpg",
    role: "Marketing Specialist",
    difficulty: "Intermediate",
    lastActivity: 1764747423,
    progress: 0,
    status: "not_registed",
    companyName: "Company D",
    skills: ["Ads", "Analytics", "DCF"],
    score: 0,
    lesson: ["Channels", "Optimization"],
  },
  {
    id: "5",
    title: "Frontend Developer Simulation",
    logo: "https://i.pinimg.com/736x/9d/9e/51/9d9e5177c40c43ab78d36de43c2db87e.jpg",
    role: "Frontend Developer",
    difficulty: "Beginner",
    lastActivity: 1764747300,
    progress: 0,
    status: "not_registed",
    companyName: "Tech Corp",
    skills: ["HTML", "CSS", "JavaScript"],
    score: 0,
    lesson: ["HTML Basic", "CSS Grid", "JS Basic"],
  },
];
